### ISSUE TITLE
how to implement authentication through this .

### ISSUE THREAD

**Issue by gmchaturvedi1** [jbrodriguez/reactorx#1]
dear, 

can you help me to implement authentication through this module. 

Regards
G.M. Chaturvedi

**Comment by jbrodriguez** [comment]
Hello @gmchaturvedi1,

Authentication is a very broad subject, for which many different implementations can be conceived.

reactorx is conceptually similar to redux, so most solutions you find for redux can be replicated with reactorx.

[This article](https://medium.com/@MattiaManzati/tips-to-handle-authentication-in-redux-4d596e11bb21#.76lld3sto) provides a guideline on how to implement authentication in redux.

It's not too difficult to see how to convert it to a reactorx implementation.

Let me know how it goes for you.
